server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/portfolio_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.error.include-message=always
server.error.include-stacktrace=always
server.address=0.0.0.0

spring.kafka.bootstrap-servers=kafka-334ef048-snethviru-9c92.e.aivencloud.com:17436
spring.kafka.properties.security.protocol=SSL
spring.kafka.ssl.trust-store-location=file:/path/to/ca.pem
spring.kafka.ssl.key-store-location=file:/path/to/client.keystore
# (ඒ වගේම certificates ටික ඔයාගේ server එකේ තියෙන්න ඕනේ)